/*
 * Project Info:  http://jcae.sourceforge.net
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 *
 * (C) Copyright 2005-2009, by EADS France
 */


package org.jcae.netbeans.mesh;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jerome Robert
 */
public class RemeshPanel extends JPanel {

    /** Creates new form RemeshPanel */
    public RemeshPanel() {
        initComponents();
		coplField.setValue(0.9);
		sizeField.setValue(100.0);
    }

	public double getCoplanarity()
	{
		return (Double) coplField.getValue();
	}

	public double getTargetSize()
	{
		return (Double) sizeField.getValue();
	}

	public boolean showDialog()
	{
		return JOptionPane.showConfirmDialog(null, this, "Remesh options",
			JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_CANCEL_OPTION;
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		GridBagConstraints gridBagConstraints;
		JLabel sizeLabel = new JLabel();
		JLabel coplLabel = new JLabel();
        sizeField = new JFormattedTextField();
        coplField = new JFormattedTextField();

        setLayout(new GridBagLayout());

        sizeLabel.setText("Target edge size");
        add(sizeLabel, new GridBagConstraints());

        coplLabel.setText("Coplanarity");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        add(coplLabel, gridBagConstraints);

        sizeField.setColumns(9);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        add(sizeField, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        add(coplField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFormattedTextField coplField;
    private JFormattedTextField sizeField;
    // End of variables declaration//GEN-END:variables

}
