set(OCE_PREFIX "" CACHE PATH "OCE prefix")
find_path(OCE_INCLUDE_DIR Standard_Version.hxx HINTS ${OCE_PREFIX}/include/oce ${OCE_PREFIX}/include)
find_library(OCE_BREP_LIBRARY TKBRep HINTS ${OCE_PREFIX}/lib ${OCE_PREFIX}/Win32/lib)
if(WIN32)
  set(OCE_DEFINITIONS -DWNT)
else() 
  set(OCE_DEFINITIONS)
endif()
get_filename_component(OCE_LIB_DIR ${OCE_BREP_LIBRARY} PATH)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OCE DEFAULT_MSG OCE_INCLUDE_DIR OCE_LIB_DIR)
