set(OCE_PREFIX "" CACHE PATH "OCE prefix")
find_path(OCE_INCLUDE_DIR Standard_Version.hxx HINTS ${OCE_PREFIX}/include/oce)
find_library(OCE_BREP_LIBRARY TKBRep HINTS ${OCE_PREFIX}/lib)
get_filename_component(OCE_LIB_DIR ${OCE_BREP_LIBRARY} PATH)
#IF (OCE_INCLUDE_DIR AND OCE_LIB_DIR)
#   SET(OCE_FOUND TRUE)
#ELSE() 
#   SET(OCE_FOUND FALSE)
#ENDIF()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OCE DEFAULT_MSG OCE_INCLUDE_DIR OCE_LIB_DIR)
